### ISSUE TITLE
change settings and crash

### ISSUE THREAD

**Issue by thawtes** [mx3L/serviceapp#13]
hi mx3l  serviceapp setup and config list, when i change wma software decoder left right button and crash image. image is openATV 6.0  pls look log lines..

01:28:46.8212 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 106 0 KEY_RIGHT RIGHT
01:28:46.8221 {   } Components/ActionMap.py:46 action action ->  SetupActions right
01:28:46.8223 { W } Components/ActionMap.py:53 action unknown action SetupActions/right! typo in keymap?
01:28:46.8228 {   } Components/ActionMap.py:46 action action ->  SetupActions right
01:28:47.3165 { D } Traceback (most recent call last):
01:28:47.3168 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 68, in action
01:28:47.3231 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 48, in action
01:28:47.3234 { D }   File "/usr/lib/enigma2/python/Components/ConfigList.py", line 243, in keyRight
01:28:47.3254 { D }   File "/usr/lib/enigma2/python/Components/ConfigList.py", line 43, in handleKey
01:28:47.3259 { D }   File "/usr/lib/enigma2/python/Components/config.py", line 376, in handleKey
01:28:47.3278 { D }   File "/usr/lib/enigma2/python/Components/config.py", line 347, in setValue
01:28:47.3281 { D }   File "/usr/lib/enigma2/python/Components/config.py", line 111, in changed
01:28:47.3284 { D }   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/ServiceApp/plugin.py", line 158, in <lambda>
01:28:47.3300 { D }   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/ServiceApp/plugin.py", line 244, in build_configlist
01:28:47.3304 { D } KeyError: 'config'
01:28:47.3308 [ E ] python/python.cpp:209 call (PyObject_CallObject(<bound method NumberActionMap.action of <Components.ActionMap.NumberActionMap instance at 0x5caf9cd8>>,('SetupActions', 'right')) failed)

pls fix it..

thank you!

**Comment by mx3L** [comment]
Hi, sorry I did forgot about this, I cannot reproduce it in openpli image.

**Comment by Tony-il-Capo** [comment]
I have the same problem trying to use serviceapp in OpenATV 6.1.
Happens when I try to switch between 'original' and 'serviceapp', so when I press left or right
As you see, same error ... "KeyError: 'config'"

> 19:52:53.0126 {   } Screens/Screen.py:151 show [SCREENNAME]  ['ServiceAppSettings', 'Setup']
19:52:53.0186 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 0 160 1
19:52:53.0203 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 352 1 KEY_OK OK
19:52:53.7360 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 69 1
19:52:53.7375 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 105 0 KEY_LEFT LEFT
19:52:53.7388 {   } Components/ActionMap.py:46 action action ->  SetupActions left
19:52:53.7391 { W } Components/ActionMap.py:53 action unknown action SetupActions/left! typo in keymap?
19:52:53.7394 {   } Components/ActionMap.py:46 action action ->  SetupActions left
19:52:53.8933 { D } Traceback (most recent call last):
19:52:53.8935 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 68, in action
19:52:53.8939 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 48, in action
19:52:53.8942 { D }   File "/usr/lib/enigma2/python/Components/ConfigList.py", line 238, in keyLeft
19:52:53.8945 { D }   File "/usr/lib/enigma2/python/Components/ConfigList.py", line 43, in handleKey
19:52:53.8948 { D }   File "/usr/lib/enigma2/python/Components/config.py", line 428, in handleKey
19:52:53.8951 { D }   File "/usr/lib/enigma2/python/Components/config.py", line 60, in setValue
19:52:53.8954 { D }   File "/usr/lib/enigma2/python/Components/config.py", line 111, in changed
19:52:53.8957 { D }   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/ServiceApp/plugin.py", line 160, in <lambda>
19:52:53.8961 { D }   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/ServiceApp/plugin.py", line 244, in build_configlist
19:52:53.8965 { D } KeyError: 'config'
19:52:53.8967 [ E ] python/python.cpp:209 call [ePyObject] (PyObject_CallObject(<bound method NumberActionMap.action of <Components.ActionMap.NumberActionMap instance at 0x58ab9aa8>>,('SetupActions', 'left')) failed)
]]>

I'm trying to see if exteplayer3 fixes a problem I have with aspect ratio in MediaPlayer (2:35:1 or wider movies are stretched to 16:9), but can't even configure it as it crashes most of times.

I've installed it from feeds, it also automatically installed ffmpeg and exteplayer3 from the official repository.

Maybe it's outdated there? is there a place where I can grab the updated files?

Thanks.

**Comment by mx3L** [comment]
Hello, I looked at this, but I don't see reason why it behaves as it behaves. It works for me on openpli. I tried to do little change in plugin.py. https://github.com/mx3L/serviceapp/commit/6ef32b91b2b47f2d6861e40be421662939c2ef5c

Try to update py file which you use as I did above and let me know if it helps, thanks.

**Comment by Tony-il-Capo** [comment]
Hi there
I'm sorry for being so late, I have little free time...

A couple days ago I've tried to re-test this but I couldn't figure out what file should I update. In ServiceApp folder there are only *.pyo files...

Maybe need to compile?

**Comment by shmox75** [comment]
Got same error on openATV 3 years later, is there a fix or an alternative ?
